apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: http-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
